### Create a new user
POST  http://localhost:8000/auth/signup
Content-Type: application/json

{
  "email": "dawud@test.fr",
  "password": "123456"
}

### Find a user by id 
GET  http://localhost:8000/auth/2
Content-Type: application/json

### Find a user by email
GET  http://localhost:8000/auth/all/dawud@test.fr
Content-Type: application/json

### FindAll users

GET  http://localhost:8000/auth
Content-Type: application/json


### Update a user
PATCH   http://localhost:8000/auth/1
Content-Type: application/json

{
  "password": "azertyuiop"
}


### Delete a user
DELETE  http://localhost:8000/auth/1
Content-Type: application/json
